name: proteus_genome_analyse_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - spades
  - prokka
  - roary
  - kraken2
  - mlst
  - raxml-ng
  - ncbi-amrfinderplus
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - r-base
  - r-ggplot2
  - r-tidyverse
